version: '3.8'

services:
  previewer:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./cache:/app/cache
    environment:
      - LRU_CACHE_SIZE=100

  nginx:
    build:
      context: .
      dockerfile: ./dockerfile.nginx
    ports:
      - "8081:80"
    volumes:
      - ./images:/usr/share/nginx/html/images
