version: '3.8'

services:
  previewer:
    environment:
      - PREVIEWER_URL=${PREVIEWER_URL}
      - NGINX_URL=${NGINX_URL}
      - LRU_CACHE_SIZE=100
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./cache:/app/cache
    networks:
      - cutit

  nginx:
    build:
      context: .
      dockerfile: ./dockerfile.nginx
    ports:
      - "8081:80"
    volumes:
      - ./images:/usr/share/nginx/html/images
    networks:
      - cutit

networks:
  cutit:
    driver: bridge
